apiVersion: apps/v1
kind: Deployment 
metadata:
  name: code-server 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels: 
        app: code-server
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: code-server
        image: 454374565233.dkr.ecr.eu-west-2.amazonaws.com/code-server:eddac92db22100169e9ec237be30a0b04a617801
        ports:
        - containerPort: 8080
        env: 
          - name: PASSWORD
            valueFrom: 
              secretKeyRef:
                name: code-server-secret
                key: PASSWORD
        volumeMounts:
        - name: data 
          mountPath: /home/coder 
      volumes: 
      - name: data
        persistentVolumeClaim:
          claimName: code-server-pvc
