name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/terraform-apply.yaml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-apply-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    env:
      AWS_REGION: eu-west-2
      TF_VAR_hosted_zone_id: ${{ secrets.TF_VAR_hosted_zone_id }}
      TF_VAR_ecr_repository_url: ${{ secrets.TF_VAR_ECR_REPOSITORY_URL }}
      TF_VAR_domain_name: codeserver.moabdullahi.uk
      TF_VAR_local_admin_arn: ${{ secrets.TF_VAR_LOCAL_ADMIN_ARN }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        run: terraform apply -auto-approve