name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-destroy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    env:
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform destroy
        run: terraform destroy -input=false -auto-approve